[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/nginx/access.log
stderr_logfile=/var/log/nginx/error.log

[program:flask]
command=python /app/backend/app_simple.py
directory=/app/backend
autostart=true
autorestart=true
user=surveillance
environment=PYTHONPATH="/app/backend",MONGO_URI="%(ENV_MONGO_URI)s",SECRET_KEY="%(ENV_SECRET_KEY)s"
stdout_logfile=/var/log/flask/access.log
stderr_logfile=/var/log/flask/error.log
